repos:
- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: pipenv run pytest
    pass_filenames: false
    language: system

  - id: mypy
    name: mypy
    entry: pipenv run mypy {{ cookiecutter.project_slug }}
    pass_filenames: false
    language: system

  - id: pylint
    name: pylint
    entry: pipenv run pylint {{ cookiecutter.project_slug }}
    pass_filenames: false
    language: system

  - id: black
    name: black
    entry: pipenv run black {{ cookiecutter.project_slug }}
    pass_filenames: false
    language: system

